### ISSUE TITLE
define notify flags for a watched file

### ISSUE THREAD

**Issue by n8behavior** [clustergarage/fim-k8s#4]
for each file watched be able to set notify flags in the CRD i.e. have different set of flags for each file being watched

**Comment by bfowle** [comment]
CRD defines a watcher as:
```
...
spec:
  selector:
    matchLabels:
      foo: bar
  subjects:
  - path: /var/log/foo
    events:
    - modify
    - open
...
```
